name: "khe-renaissance"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=khe
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d khe"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_internal

  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/khe
      - ORIGIN=http://0.0.0.0:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.khe-renaissance-web.rule=Host(`khe.io`)"
      - "traefik.http.routers.khe-renaissance-web.entrypoints=web"
      - "traefik.http.services.khe-renaissance-web.loadbalancer.server.port=3000"
      - "traefik.http.services.khe-renaissance-web.service=khe-renaissance-web"
      - "traefik.http.routers.khe-renaissance-websecure.rule=Host(`khe.io`)"
      - "traefik.http.routers.khe-renaissance-websecure.entrypoints=websecure"
      - "traefik.http.services.khe-renaissance-websecure.loadbalancer.server.port=3000"
      - "traefik.http.services.khe-renaissance-websecure.service=khe-renaissance-websecure"
      - "traefik.http.routers.khe-renaissance-websecure.tls.certresolver=letsencrypt"
    networks:
      - app_internal
      - traefik

networks:
  app_internal:
  traefik:
    external: true

volumes:
  db_data: